name: turbo_jet
description: "Turbo jet engine mobile control app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  http: ^1.4.0
  speedometer_chart: ^1.0.8
  async: ^2.11.0
  get: ^4.6.6
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.3.3
  firebase_app_check: ^0.3.1+4
  firebase_auth: ^5.3.1
  firebase_core: ^3.14.0
  flutter_native_splash: ^2.4.0
  icons_launcher: ^3.0.1
  auto_size_text: ^3.0.0
  lottie: ^3.3.1
  animated_snack_bar: ^0.4.0
  calendar_date_picker2: ^1.1.7
  dropdown_button2: ^2.3.9
  connectivity_plus: ^6.1.0
  internet_connection_checker_plus: ^2.5.2
  sign_button: ^2.0.6
  stylish_bottom_bar: ^1.1.1
  flutter_animated_button: ^2.0.4
  just_audio: ^0.10.4
  pull_to_refresh: ^2.0.0
  flutter_staggered_animations: ^1.1.1

icons_launcher:
  image_path: "assets/images/logo.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.jpg
  #branding: assets/images/logo.jpg
  color_dark: "#121212"
  image_dark: assets/images/logo.jpg
  #branding_dark: assets/images/logo.jpg

  android_12:
    image: assets/images/logo.jpg
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.jpg
    icon_background_color_dark: "#121212"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie_animations/
    - assets/sounds/